groups:
- name: prometheus_nginxlog_exporter
  rules:
  - record: job:prometheus_nginxlog_exporter:status_4xx_1m
    expr: sum(rate(nginx_http_response_count_total{status=~"4.."}[1m]))
  - record: job:prometheus_nginxlog_exporter:status_total_1m
    expr: sum(rate(nginx_http_response_count_total[1m]))
  - alert: ErrorStatusAndFailRate
    expr: | 
      (job:prometheus_nginxlog_exporter:status_4xx_1m >= 10)
      and
      (
        (job:prometheus_nginxlog_exporter:status_4xx_1m)
        / 
        job:prometheus_nginxlog_exporter:status_total_1m 
        * 100
      ) >= 50
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      summary: 'Error Status Code Bigger than 10 And Fail Rate Higher than 50%'  