{
 "title": "Monitoring System - CollectD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type)(rate(collectd_cpu_total[5m]))",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (memory) (rate(collectd_memory[5m]))",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "Interface Dropped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(collectd_interface_if_dropped_rx_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "eth_rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_dropped_tx_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "eth_tx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_dropped_rx_total{interface=\"lo\"}[5m]))",
     "legendFormat": "lo_rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_dropped_tx_total{interface=\"lo\"}[5m]))",
     "legendFormat": "lo_tx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_dropped_rx_total{interface=\"docker0\"}[5m]))",
     "legendFormat": "docker0-rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_dropped_tx_total{interface=\"docker0\"}[5m]))",
     "legendFormat": "docker0-tx"
    }
   ]
  },
  {
   "title": "Interface errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(collectd_interface_if_errors_rx_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "eth_rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_errors_tx_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "eth_tx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_errors_rx_total{interface=\"lo\"}[5m]))",
     "legendFormat": "lo_rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_errors_tx_total{interface=\"lo\"}[5m]))",
     "legendFormat": "lo_tx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_errors_rx_total{interface=\"docker0\"}[5m]))",
     "legendFormat": "docker0-rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_errors_tx_total{interface=\"docker0\"}[5m]))",
     "legendFormat": "docker0-tx"
    }
   ]
  },
  {
   "title": "Interface octets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(collectd_interface_if_octets_rx_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "eth_rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_octets_tx_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "eth_tx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_octets_rx_total{interface=\"lo\"}[5m]))",
     "legendFormat": "lo_rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_octets_tx_total{interface=\"lo\"}[5m]))",
     "legendFormat": "lo_tx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_octets_rx_total{interface=\"docker0\"}[5m]))",
     "legendFormat": "docker0-rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_octets_tx_total{interface=\"docker0\"}[5m]))",
     "legendFormat": "docker0-tx"
    }
   ]
  },
  {
   "title": "Interface packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(collectd_interface_if_packets_rx_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "eth_rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_packets_tx_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "eth_tx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_packets_rx_total{interface=\"lo\"}[5m]))",
     "legendFormat": "lo_rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_packets_tx_total{interface=\"lo\"}[5m]))",
     "legendFormat": "lo_tx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_packets_rx_total{interface=\"docker0\"}[5m]))",
     "legendFormat": "docker0-rx"
    },
    {
     "expr": "sum (rate(collectd_interface_if_packets_tx_total{interface=\"docker0\"}[5m]))",
     "legendFormat": "docker0-tx"
    }
   ]
  }
 ]
}