version: "3"

services:  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules/node_exporter_rules.yml:/etc/prometheus/rules/node_exporter_rules.yml
    ports:
      - 9090:9090

  node1:
    container_name: node1
    image: prom/node-exporter
  node2:
    container_name: node2
    image: prom/node-exporter
  node3:
    container_name: node3
    image: prom/node-exporter
  node4:
    container_name: node4
    image: prom/node-exporter

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
  
  app:
    container_name: app
    image: app
    build: ./app
    ports:
      - "8080:8080"