{
 "title": "Monitoring HTTP Server - NGINX(nginxlog-exporter)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(nginx_parse_errors_total, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(nginx_parse_errors_total{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total[1m]))",
     "legendFormat": "rps trend"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total[1m] offset 1d))",
     "legendFormat": "rps past day"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total[1m] offset 1w))",
     "legendFormat": "rps past week"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(status:nginx_http_response_count_total:success_1m / sum(rate(nginx_http_response_count_total[1m]))) * 100",
     "legendFormat": "success rate"
    },
    {
     "expr": "(status:nginx_http_response_count_total:400_404_1m / sum(rate(nginx_http_response_count_total[1m]))) * 100",
     "legendFormat": "400-404 rate"
    },
    {
     "expr": "(status:nginx_http_response_count_total:4xx_1m / sum(rate(nginx_http_response_count_total[1m]))) * 100",
     "legendFormat": "4xx rate"
    },
    {
     "expr": "(status:nginx_http_response_count_total:5xx_1m / sum(rate(nginx_http_response_count_total[1m]))) * 100",
     "legendFormat": "5xx rate"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "status:nginx_http_response_count_total:2xx_1m",
     "legendFormat": "2xx"
    },
    {
     "expr": "status:nginx_http_response_count_total:3xx_1m",
     "legendFormat": "3xx"
    },
    {
     "expr": "status:nginx_http_response_count_total:4xx_1m",
     "legendFormat": "4xx"
    },
    {
     "expr": "status:nginx_http_response_count_total:5xx_1m",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_response_time_seconds:avg_1m",
     "legendFormat": "{{method}}-{{request_uri}}"
    }
   ]
  }
 ]
}