global:
  # slack_api_url: '' # <전역 설정>

route:
  receiver: 'webhook'
  repeat_interval: 2m
  group_interval: 10s
  group_wait: 5s

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: http://app:8080/

  - name: 'slack'
    slack_configs:
    - channel: '#_monitoring'
      api_url: '' # 리시버 개별 설정
      send_resolved: true 
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"